AWSTemplateFormatVersion: 2010-09-09
Description: Create basic Infra with a VPC, private subnets and public subnets for EKS.
Parameters:
  EnvironmentPrefix:
    Type: String
    Default: dev
    Description: Prefix for Env Name
  VpcBlock:
    Type: String
    Default: 192.168.0.0/16
    Description: The CIDR range for the VPC. This should be a valid private (RFC 1918) CIDR range.    
  Subnet01Block:
    Type: String
    Default: 192.168.1.0/24
    Description: CidrBlock for subnet 01 within the VPC
  Subnet02Block:
    Type: String
    Default: 192.168.2.0/24
    Description: CidrBlock for subnet 02 within the VPC    
  Subnet03Block:
    Type: String
    Default: 192.168.3.0/24
    Description: CidrBlock for subnet 03 within the VPC    
  Subnet04Block:
    Type: String
    Default: 192.168.4.0/24
    Description: CidrBlock for subnet 04 within the VPC    
  Subnet05Block:
    Type: String
    Default: 192.168.5.0/24
    Description: CidrBlock for subnet 05 within the VPC    
  Subnet06Block:
    Type: String
    Default: 192.168.6.0/24
    Description: CidrBlock for subnet 06 within the VPC                    

# Subnet01 to Subnet03 will contain Nodes which will run our Pods.
# Subnet04 to Subnet06 will contain K8 load balancers which Kubernetes will manage, these will load balance traffic to 
# our pods in Subnet01 to Subnet03.

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Specify an already created keypair. KeyPair cannot be created using CF, create it in AWS console
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0e306788ff2473ccb
    Description: Specify AMI ID for the EC2 Instance., the default AMI is Amazon linux2 based  

Conditions:
  IsMumbaiRegion: !Equals [ !Ref 'AWS::Region', ap-south-1 ]        

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-VPC'


  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Private-RT'
        - Key: Network
          Value: Private
          

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Public-RT'
        - Key: Network
          Value: Public          

  Subnet01:
    Type: AWS::EC2::Subnet
    Metadata:
      Comment: Subnet 01, a private subnet
    Properties:
      AvailabilityZone: !If [ IsMumbaiRegion, ap-south-1a, !Select [0,  Fn::GetAZs: !Ref 'AWS::Region' ]   ] #currently t2.micro not supported in ap-south-1c hence this logic
      CidrBlock: !Ref Subnet01Block
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Private-Subnet01'

  Subnet02:
    Type: AWS::EC2::Subnet
    Metadata:
      Comment: Subnet 02, a private subnet
    Properties:
      AvailabilityZone: !If [ IsMumbaiRegion, ap-south-1b, !Select [0,  Fn::GetAZs: !Ref 'AWS::Region' ]   ] 
      CidrBlock: !Ref Subnet02Block
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Private-Subnet02'

  Subnet03:
    Type: AWS::EC2::Subnet
    Metadata:
      Comment: Subnet 03, a private subnet
    Properties:
      AvailabilityZone: !If [ IsMumbaiRegion, ap-south-1b, !Select [0,  Fn::GetAZs: !Ref 'AWS::Region' ]   ] 
      CidrBlock: !Ref Subnet03Block
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Private-Subnet03'                    

  Subnet04:
    Type: 'AWS::EC2::Subnet'
    Metadata:
      Comment: Subnet 04, a public subnet which will have NATGateway
    Properties:
      AvailabilityZone: !If [ IsMumbaiRegion, ap-south-1a, !Select [1, Fn::GetAZs: !Ref 'AWS::Region' ]   ] 
      CidrBlock: !Ref Subnet04Block
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Public-Subnet04'


  Subnet05:
    Type: 'AWS::EC2::Subnet'
    Metadata:
      Comment: Subnet 05, a public subnet
    Properties:
      AvailabilityZone: !If [ IsMumbaiRegion, ap-south-1b, !Select [1, Fn::GetAZs: !Ref 'AWS::Region' ]   ] 
      CidrBlock: !Ref Subnet05Block
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Public-Subnet05'

  Subnet06:
    Type: 'AWS::EC2::Subnet'
    Metadata:
      Comment: Subnet 06, a public subnet
    Properties:
      AvailabilityZone: !If [ IsMumbaiRegion, ap-south-1b, !Select [1, Fn::GetAZs: !Ref 'AWS::Region' ]   ] 
      CidrBlock: !Ref Subnet06Block
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-Public-Subnet06'          


  Subnet01RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet01
      RouteTableId: !Ref RouteTable

  Subnet02RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet02
      RouteTableId: !Ref RouteTable

  Subnet03RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet03
      RouteTableId: !Ref RouteTable            

  Subnet04RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet04
      RouteTableId: !Ref PublicRouteTable

  Subnet05RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet05
      RouteTableId: !Ref PublicRouteTable      

  Subnet06RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet06
      RouteTableId: !Ref PublicRouteTable         
      
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-IG'
          
  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC             

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment #DependsOn ensures that NatGateway is created only after Internet gateway is attached to the VPC

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-NG'
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref Subnet04 

  NatGateway2:
      Type: AWS::EC2::NatGateway
      Properties:
        Tags:
          - Key: Name
            Value: !Sub '${EnvironmentPrefix}-NG'
        AllocationId: !GetAtt NatGateway1EIP.AllocationId
        SubnetId: !Ref Subnet05

  NatGateway3:
      Type: AWS::EC2::NatGateway
      Properties:
        Tags:
          - Key: Name
            Value: !Sub '${EnvironmentPrefix}-NG'
        AllocationId: !GetAtt NatGateway1EIP.AllocationId
        SubnetId: !Ref Subnet06      

   
  RouteToIG:
    DependsOn: VPCGatewayAttachment
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway


Outputs:
    VPC: 
      Value: !Ref VPC                    
